### ISSUE TITLE
data.items datetime is timestamp without time zone

### ISSUE THREAD

**Issue by bitner** [arturo-ai/arturo-stac-api#100]
Timestamp without time zone should always be avoided as it is ambiguous as to the timezone represented by the field and can be lossy at the DST transition time.

**Comment by kylebarron** [comment]
Since the STAC spec defines timestamps as always being in UTC, is it still necessary to store the timezone? https://github.com/radiantearth/stac-spec/blob/4988a40f6071666d345e4a1c5adc9a6338973769/item-spec/item-spec.md#properties-object
