### ISSUE TITLE
Delete collection fails with 'collection does not exist'

### ISSUE THREAD

**Issue by kylebarron** [arturo-ai/arturo-stac-api#78]
```py
r = requests.delete('http://localhost:8081/collections/sentinel-s2-l2a')
r.json()
# {'detail': 'collection does not exist'}
```

But the collection does exist

```py
r = requests.get('http://localhost:8081/collections/sentinel-s2-l2a')
r.json()
```

```py
{'id': 'sentinel-s2-l2a',
 'description': 'Sentinel-2a and Sentinel-2b imagery, processed to Level 2A (Surface Reflectance)',
 'stac_version': '1.0.0-beta.2',
```

**Comment by kylebarron** [comment]
I think I found my issue here. I assumed that if you did an HTTP `DELETE` request on a collection it would delete all the items in the collection, but that’s not the case.

Here I tried to delete a collection that contains some items:
![image](https://user-images.githubusercontent.com/15164633/106992343-72177680-6735-11eb-93d8-b90ee95165e6.png)

Here's the log from the server:
![image](https://user-images.githubusercontent.com/15164633/106992368-83608300-6735-11eb-9cf7-cfb37de8c004.png)

So I gather that it's necessary to first delete all the items before you delete the collection. It would also be nicer to respond with a more accurate error message, since the collection does indeed exist.

**Comment by kylebarron** [comment]
Once I've deleted all rows in `data.items` where `collection_id` equals the identifier, then the `DELETE` request works fine.

**Comment by geospatial-jeff** [comment]
Sqlalchemy has support for a delete cascade which deletes all of the children first, but we decided not to implement it for reasons I can't remember at the moment.

> It would also be nicer to respond with a more accurate error message, since the collection does indeed exist.

We are definitely overloading the `ForeignKeyViolation` (https://github.com/arturo-ai/arturo-stac-api/blob/7d4c9572981e935de2521441878f3ffb78f6b9b7/stac_api/clients/postgres/session.py#L30-L31) exception.  I'll create an issue for this.
