### ISSUE TITLE
Make migration depend on stac-api in docker compose?

### ISSUE THREAD

**Issue by kylebarron** [arturo-ai/arturo-stac-api#79]
The `migration` `command` in `docker-compose.yml` is:
https://github.com/arturo-ai/arturo-stac-api/blob/4f0ba30a2300fc3273aca83ed6e118def2529b75/docker-compose.yml#L48-L49

It looks like the `sleep 10` is just to make sure the `app` service is deployed first? Could you just add 
```
    depends_on:
      - database
      - app
```
to the migration config? Or would that not work?

**Comment by geospatial-jeff** [comment]
`depends_on` doesn't want until the container is "ready", just that it has started.  And the postgres container will of course do some initialization after it has started.  The docs reccomend doing this: https://docs.docker.com/compose/startup-order/, but I've found that sleep statements are more reliable.
